name: build

on:
  push:
    branches:
      - '*'
      - '!release-*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - name: npm install (google-pay-psp-client)
        run: |
          cd google-pay-psp-client
          npm install
      - name: npm test (google-pay-psp-client)
        run: |
          cd google-pay-psp-client
          npm test
